### ISSUE TITLE
Tweak not working at all

### ISSUE THREAD

**Issue by Iphone5-RecoveryMode** [tomaszpoliszuk/MagSafeController#13]
I have an iPhone 7 on 14.2, and for some reason the tweak isn't working. I had restored rootfs and don't have any other tweak installed.

**Comment by tomaszpoliszuk** [comment]
Could you please provide more information?
What settings you chosen in tweak preferences?

**Comment by Iphone5-RecoveryMode** [comment]
I used the default settings and didn't touch anything in it

**Comment by tomaszpoliszuk** [comment]
Does it happen on Checkra1n?

Could you try if other tweaks are working?

**Comment by Iphone5-RecoveryMode** [comment]
other tweaks work, im using stock checkra1n.

**Comment by tomaszpoliszuk** [comment]
Could you try this:

- reinstall tweak

- switch options between Custom and Native mode

I'll reinstall my 6s this weekend to recreate your situation (clean iOS on Checkra1n with only MagSafe Controller installed) if it's still not working.

**Comment by tomaszpoliszuk** [comment]
Sorry - didn't had time to reinstall my 6s yet - could you try what i said in previous comment and let me know if that worked?

Additionally could you try if [MagSafe Enabler](http://cydia.saurik.com/package/com.tomaszpoliszuk.lockscreenbatterymagsafe/) is working for you?

**Comment by juliocormor** [comment]
Do you have a custom lock screen? I was about to open a compatibility issue with Kalm.

**Comment by tomaszpoliszuk** [comment]
Closed due to lack of response.
