### ISSUE TITLE
[Request] Build this tweak for ARM64e

### ISSUE THREAD

**Issue by IORose** [tomaszpoliszuk/MagSafeController#17]
![610DC386-D93D-4513-88ED-F5ECB3087E4F](https://user-images.githubusercontent.com/70447619/118403887-34ea4b00-b679-11eb-9f6a-9fcfbf013b79.png)
Hello, I have this device:
iPhone 11
iOS 13.5
unc0ver 5.3.1

I can’t use this tweak due to the lack of support ARM64e arch. 
Thanks.

**Comment by tomaszpoliszuk** [comment]
Sorry - I've changed build settings for testing in my profile and forgot to revert it - could you verify if ~this version~ (link removed) works correctly?

**Comment by IORose** [comment]
> Sorry - I've changed build settings for testing in my profile and forgot to revert it - could you verify if ~~[this version]~~(link removed) works correctly?

<details>
  <summary>Screenshots</summary>
  

![1795827A-57A9-4686-9E85-C9700444E2BE](https://user-images.githubusercontent.com/70447619/118480577-19378100-b71b-11eb-949f-e7ba76bf5071.png)
</details>

Hello. It seems like nothing changed.

**Comment by tomaszpoliszuk** [comment]
Could you try this two test builds then:

~test 2~ (link removed) - Xcode 11.7 toolchain compiled for both arm64 & arm64e

~test 3~ (link removed) - Xcode 12.4 toolchain compiled for arm64 (but probably can work on arm64e)

**Comment by IORose** [comment]
> ~~[test 2]~~(link removed) - Xcode 11.7 toolchain compiled for both arm64 & arm64e

com.tomaszpoliszuk.applibrarycontroller:
 com.tomaszpoliszuk.applibrarycontroller depends on firmware (>= 14.0); however:
  Version of firmware on system is 13.5.

It’s not the MagSafe Controller. Its applibrarycontroller, which can’t be supported on iOS 13.

**Comment by tomaszpoliszuk** [comment]
Sorry - I've grabbed wrong links - here are correct ones:

[test 2](http://tomaszpoliszuk.com/files/jailbreak/testing/com.tomaszpoliszuk.magsafecontroller_1.1.3-2%2Bdebug_iphoneos-arm.deb) - Xcode 11.7 toolchain compiled for both arm64 & arm64e

[test 3](http://tomaszpoliszuk.com/files/jailbreak/testing/com.tomaszpoliszuk.magsafecontroller_1.1.3-3%2Bdebug_iphoneos-arm.deb) - Xcode 12.4 toolchain compiled for arm64 (but probably can work on arm64e)

(additionally could you remove original links from your comments?)

**Comment by IORose** [comment]
> Sorry - I've grabbed wrong links - here are correct ones:
> [test 2](http://tomaszpoliszuk.com/files/jailbreak/testing/com.tomaszpoliszuk.magsafecontroller_1.1.3-2%2Bdebug_iphoneos-arm.deb) - Xcode 11.7 toolchain compiled for both arm64 & arm64e

This version works fine: 

<details>
  <summary>Screenshots</summary>

![IMAGE 2021-05-19 18:41:28](https://user-images.githubusercontent.com/70447619/118842378-d2d85280-b8d1-11eb-9843-3f391f2789f4.jpg)

![IMAGE 2021-05-19 18:41:24](https://user-images.githubusercontent.com/70447619/118842371-d10e8f00-b8d1-11eb-9f54-3a5d230f4d3e.jpg)> 
</details>

> [test 3](http://tomaszpoliszuk.com/files/jailbreak/testing/com.tomaszpoliszuk.magsafecontroller_1.1.3-3%2Bdebug_iphoneos-arm.deb) - Xcode 12.4 toolchain compiled for arm64 (but probably can work on arm64e)

This version is giving me an error like before. (arm64 dylibs cannot be loaded into arm64e processes)

> (additionally could you remove original links from your comments?)

Sure.

**Comment by tomaszpoliszuk** [comment]
Sweet, please use test 2 for now - I'll submit update today to fix this issue and I'll close it when update will be published.
Thank you for reporting and help in testing!

Have a nice day!

**Comment by IORose** [comment]
> Have a nice day!

Thank you for your support!
